@startuml
actor caller 
caller -> UniswapV2Factory: UniswapV2Factory.createPair(address,address) 
 alt require 

	 UniswapV2Factory -> UniswapV2Factory:  revert 
 else continue 
 end 
 
 alt require 

	 UniswapV2Factory -> UniswapV2Factory:  revert 
 else continue 
 end 

note over UniswapV2Factory: SLOADs: \n   - getPair 
 alt require 

	 UniswapV2Factory -> UniswapV2Factory:  revert 
 else continue 
 end 
 
 UniswapV2Factory -> UniswapV2Factory: type(address) 
 UniswapV2Factory -> UniswapV2Factory: abi.encodePacked() 
 UniswapV2Factory -> UniswapV2Factory: keccak256(bytes) 
UniswapV2Factory -> UniswapV2Pair: initialize(address,address)
note over UniswapV2Pair: SLOADs: \n   - factory 
 alt require 

	 UniswapV2Pair -> UniswapV2Pair:  revert 
 else continue 
 end 
 
note over UniswapV2Pair #A9DCDF: SSTOREs: \n   - token0 
note over UniswapV2Pair #A9DCDF: SSTOREs: \n   - token1 
UniswapV2Factory -> UniswapV2Pair: initialize(address,address) 
 UniswapV2Factory <- UniswapV2Pair: return initialize(address,address) 
note over UniswapV2Factory #A9DCDF: SSTOREs: \n   - getPair 
note over UniswapV2Factory #A9DCDF: SSTOREs: \n   - getPair
note over UniswapV2Factory: SLOADs: \n   - allPairs 
note over UniswapV2Factory #A9DCDF: SSTOREs: \n   - allPairs
note over UniswapV2Factory: SLOADs: \n   - allPairs
@enduml