@startuml
actor caller 
caller -> UniswapV2Factory: UniswapV2Factory.createPair(address,address)
note over UniswapV2Factory: SLOADs: \n   - getPair 
UniswapV2Factory -> UniswapV2Pair: initialize(address,address)
note over UniswapV2Pair: SLOADs: \n   - factory 
note over UniswapV2Pair #A9DCDF: SSTOREs: \n   - token0 
note over UniswapV2Pair #A9DCDF: SSTOREs: \n   - token1 
 UniswapV2Factory <- UniswapV2Pair: return initialize(address,address) 
note over UniswapV2Factory #A9DCDF: SSTOREs: \n   - getPair 
note over UniswapV2Factory #A9DCDF: SSTOREs: \n   - getPair
note over UniswapV2Factory: SLOADs: \n   - allPairs 
note over UniswapV2Factory #A9DCDF: SSTOREs: \n   - allPairs
note over UniswapV2Factory: SLOADs: \n   - allPairs 
 UniswapV2Pair -> UniswapV2Pair: lock() 
 UniswapV2Pair -> UniswapV2Pair: getReserves() 
 UniswapV2Pair -> UniswapV2Pair: _mintFee(uint112,uint112) 
 UniswapV2Pair -> UniswapV2Pair: _mint(address,uint256) 
 UniswapV2Pair -> UniswapV2Pair: require(bool,string) 
 UniswapV2Pair -> UniswapV2Pair: _mint(address,uint256) 
 UniswapV2Pair -> UniswapV2Pair: _update(uint256,uint256,uint112,uint112)
@enduml